image: node:latest

# CI config is based on frontend-mobile#7
# Some stage and build steps are missed due to lacking of resource (hardware, accounts), will be
# added once things ready.

stages:
  - lint
  - test
  - build

before_script:
  # Set up environment variables with fastlane
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8

  # # configure secrets!
  # - echo "$RELEASE_KEY_DATA" | base64 -di > android/app/my-release-key.keystore
  # - echo "$JSON_KEY_DATA" > android/fastlane/g-secrect.json

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - android/.gradle/
    - node_modules/

# --------------------------------------------------------------------------------
# STAGE LINT
# --------------------------------------------------------------------------------

# - Check for coding style.
# - Should run before all other step every build, and for every branch, to
#   enforce consistent coding style.
lint:
  stage: lint
  script:
    - yarn
    - yarn lint

# --------------------------------------------------------------------------------
# STAGE TEST
# --------------------------------------------------------------------------------

unit-test:
  stage: test
  script:
    - yarn
    # run test and also generate coverage report
    - yarn test:coverage
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_CI_COMMIT_SHA"
    paths:
      - coverage
    expire_in: 1 week

# --------------------------------------------------------------------------------
# STAGE BUILD
# --------------------------------------------------------------------------------

build-android:
  image: webcuisine/gitlab-ci-react-native-android
  stage: build
  script:
    - yarn build:android:debug
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_CI_COMMIT_SHA"
    when: on_success
    paths:
      - android/app/build/outputs/apk/
    expire_in: 1 yrs
  only:
    - master
    - dev
